cc_binary(
    name = "voice_lab",
    srcs = ["voice_lab.cc"],
    deps = [
        "//omni/base:io_types",
        "//omni/tts:tts_engine",
        "//omni/tts:tts_session",
        "//omni/tts:stream_text_source",
        "//omni/tts/kokoro:kokoro_model_config",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
    ],
)
